[pytest]
pythonpath = blogicum/ .
DJANGO_SETTINGS_MODULE = blogicum.settings
norecursedirs = .venv/* env/* venv/*
addopts = -rE -vv --show-capture=no -p no:cacheprovider
testpaths = tests/
python_files = test_*.py
django_debug_mode = true
